name: Build Image
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'build-wine.sh'
      - 'Containerfile'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Buildah Action
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: wine-builder
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        extra-args: |
          --disable-content-trust

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"
    
    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"
